# Generated by Django 6.0.2 on 2026-02-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_embedding_dimension_384'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='documentchunk',
            new_name='knowledge_d_organiz_9e0a15_idx',
            old_name='knowledge_do_organiz_4a0b0d_idx',
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Chunk order within document'),
        ),
    ]
